# Generated by Django 6.0.5 on 2026-05-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
