# Generated by Django 6.0.5 on 2026-05-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_builder', '0002_resume_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
