SKILLS_DB = [
    "python",
    "django",
    "flask",
    "react",
    "mongodb",
    "mysql",
    "postgresql",
    "javascript",
    "html",
    "css",
    "tailwind",
    "docker",
    "aws",
    "git",
    "github",
    "rest api",
    "machine learning",
    "data analysis",
    "pandas",
    "numpy",
]